apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    name: postgres-deploy
    app: auth-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: auth-app
    spec:
      containers:
        - name: postres-image
          image: {{ .Values.container.image }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.container.env.user }} 
            - name: POSTGRES_PASSWORD
              value: {{ .Values.container.env.pass }}
            - name: POSTGRES_DB
              value: {{ .Values.container.env.db }}
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust       
                  